### ISSUE TITLE
rate/amount limit of the unoffical api

### ISSUE THREAD

**Issue by complexly** [Vaayne/notionai-py#1]
Thank you for creating this wrap of unoffical API!
I was using the API to generate summaries of text in batch, do you know what the rate/amount limit is? My access seems blocked after hundreds of requests at a very low rate (<10 RPM), thanks!

**Comment by vaayne** [comment]
Based on [Notion's FAQ](https://www.notion.so/help/ai-pricing-and-usage#ai-usage-limits), it is not clear how much usage is allowed. 
However, it seems that if you use it more than 30 times a day, it will respond slower.
