### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Changer119** [Vaayne/notionai-py#2]
I am a Python novice and have installed notionai-py using pip3 according to your instructions. However, I encountered this error when executing [main.py]
![image](https://user-images.githubusercontent.com/4286345/230336173-25e5355b-a0f9-4d33-b8a1-4e70a0cdc0f3.png)

I am using a Mac computer with Python 3.8 installed, and I have followed Notion's [official instructions](https://developers.notion.com/docs/authorization
) to create an integration and a database. The corresponding token and database_id are both ready.

**Comment by vaayne** [comment]
Please follow these [instructions](https://github.com/Vaayne/notionai-py#get-notion-token-and-workspace-id) to obtain a token. It is not the integration token secret for Notion

**Comment by Changer119** [comment]
after i update python from 3.8 to 3.10 , the problem has been sovled .

refer to https://github.com/yonatan8070/homelab-fetch/issues/1

**Comment by complexly** [comment]
Python version problem. Adding the following line to the source code will resolve the issue in old python:
`from __future__ import annotations`

**Comment by vaayne** [comment]
Thanks @complexly 
@Changer119 fixed in https://github.com/Vaayne/notionai-py/commit/5123be5725f37cca5cdea56313ab88b4295c6bd2, please update to latest version
