### ISSUE TITLE
BASIC Example:ValidationError:Invalid inpu

### ISSUE THREAD

**Issue by flotufox** [Vaayne/notionai-py#3]
1. installed successfully
2. tested : print(spaces) returned with right response: [{'id': 'xxxxxx', 'name': 'xxxxxxx'}]
3. run example code BASIC , tried to print(res), returned error :
data: {"errorId":"xxxxxxxxxxxxx","name":"ValidationError","message":"Invalid input."}, error: 'type'
Could anyone tell me where the problem is?

**Comment by vaayne** [comment]
Could you please share the full code you are running? I have not encountered any issues, but having the complete code would help me understand your process better.
@flotufox

**Comment by flotufox** [comment]
issue solved, it seems that i should use the space id directly, not as a enviroment variable.
