### ISSUE TITLE
not working now...

### ISSUE THREAD

**Issue by flotufox** [Vaayne/notionai-py#5]
It works pretty well in months.
but today, it doesn't work.
when i try to use ai.help_me_write or some other fuctions, it says like this:
(data: {"errorId":"b2a1b4b6-f8a3-4273-a11b-c493ce4701fd","name":"ValidationError","debugMessage":"Invalid input.","message":"Something went wrong. (400)"}, error: 'type')

**Comment by vaayne** [comment]
@flotufox  NotionAI has recently upgraded its model to openai-4, causing some compatibility issues. To resolve this, please update to the latest version by running `pip install --upgrade notionai-py`.

**Comment by flotufox** [comment]
sad...
updated to 0.1.5
but still not working...
