### ISSUE TITLE
"name":"ValidationError","debugMessage":"Invalid input.","message":"Something went wrong. (400)"}, error: 'type'

### ISSUE THREAD

**Issue by ssy040504** [Vaayne/notionai-py#6]
"name":"ValidationError","debugMessage":"Invalid input.","message":"Something went wrong. (400)"}, error: 'type'

**Comment by vaayne** [comment]
@ssy040504 In the latest version, a fix has been released. Please update Notion AI Python by running the following command: `pip install --upgrade notionai-py`
